-- Creates the Assets folder
-- Generated by Codify from Anthony O'Brien's original plugin

return function(): Folder
	local Assets = Instance.new("Folder")
	Assets.Name = "Assets"

	local ControlPoint = Instance.new("Part")
	ControlPoint.Name = "ControlPoint"
	ControlPoint.Anchored = true
	ControlPoint.BottomSurface = Enum.SurfaceType.Smooth
	ControlPoint.BrickColor = BrickColor.new("Really red")
	ControlPoint.CFrame = CFrame.new(-3034.70312, 6.30002689, 7350.29688, 1, 0, 0, 0, 1, 0, 0, 0, 1)
	ControlPoint.CastShadow = false
	ControlPoint.Color = Color3.fromRGB(255, 0, 0)
	ControlPoint.Material = Enum.Material.SmoothPlastic
	ControlPoint.Size = Vector3.new(6, 2, 2)
	ControlPoint.TopSurface = Enum.SurfaceType.Smooth

	local Gui = Instance.new("BillboardGui")
	Gui.Name = "Gui"
	Gui.Active = true
	Gui.AlwaysOnTop = true
	Gui.ClipsDescendants = true
	Gui.LightInfluence = 1
	Gui.Size = UDim2.fromScale(3, 3)
	Gui.StudsOffset = Vector3.new(0, 3, 0)
	Gui.ZIndexBehavior = Enum.ZIndexBehavior.Sibling

	local Number = Instance.new("TextLabel")
	Number.Name = "Number"
	Number.FontFace =
		Font.new("rbxasset://fonts/families/GothamSSm.json", Enum.FontWeight.Medium, Enum.FontStyle.Normal)
	Number.Text = "Control Point"
	Number.TextColor3 = Color3.fromRGB(240, 240, 240)
	Number.TextScaled = true
	Number.TextSize = 14
	Number.TextStrokeTransparency = 0
	Number.TextWrapped = true
	Number.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	Number.BackgroundTransparency = 1
	Number.BorderSizePixel = 0
	Number.Size = UDim2.fromScale(1, 1)
	Number.Parent = Gui

	Gui.Parent = ControlPoint

	local UpArrow = Instance.new("Decal")
	UpArrow.Name = "Up Arrow"
	UpArrow.Texture = "http://www.roblox.com/asset/?id=29563813"
	UpArrow.Face = Enum.NormalId.Back
	UpArrow.Parent = ControlPoint

	local DownArrow = Instance.new("Decal")
	DownArrow.Name = "Down Arrow"
	DownArrow.Texture = "http://www.roblox.com/asset/?id=29563831"
	DownArrow.Face = Enum.NormalId.Top
	DownArrow.Parent = ControlPoint

	ControlPoint.Parent = Assets

	local Gui1 = Instance.new("Frame")
	Gui1.Name = "Gui"
	Gui1.BackgroundColor3 = Color3.fromRGB(44, 44, 44)
	Gui1.Size = UDim2.fromScale(1, 1)
	Gui1.ZIndex = 0

	local UIPadding = Instance.new("UIPadding")
	UIPadding.Name = "UIPadding"
	UIPadding.PaddingBottom = UDim.new(0, 10)
	UIPadding.PaddingLeft = UDim.new(0, 10)
	UIPadding.PaddingRight = UDim.new(0, 10)
	UIPadding.PaddingTop = UDim.new(0, 10)
	UIPadding.Parent = Gui1

	local CreateButton = Instance.new("TextButton")
	CreateButton.Name = "CreateButton"
	CreateButton.FontFace =
		Font.new("rbxasset://fonts/families/GothamSSm.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
	CreateButton.Text = "Render"
	CreateButton.TextColor3 = Color3.fromRGB(248, 248, 248)
	CreateButton.TextSize = 14
	CreateButton.TextWrapped = true
	CreateButton.AnchorPoint = Vector2.new(0.5, 1)
	CreateButton.BackgroundColor3 = Color3.fromRGB(54, 54, 54)
	CreateButton.BorderColor3 = Color3.fromRGB(45, 45, 45)
	CreateButton.Position = UDim2.fromScale(0.5, 0.95)
	CreateButton.Size = UDim2.fromScale(0.4, 0.1)
	CreateButton.Parent = Gui1

	local Length = Instance.new("Frame")
	Length.Name = "Length"
	Length.AnchorPoint = Vector2.new(0.5, 0.5)
	Length.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	Length.BackgroundTransparency = 1
	Length.Position = UDim2.fromScale(0.5, 0.6)
	Length.Size = UDim2.fromScale(1, 0.08)

	local TextLabel = Instance.new("TextLabel")
	TextLabel.Name = "TextLabel"
	TextLabel.FontFace =
		Font.new("rbxasset://fonts/families/GothamSSm.json", Enum.FontWeight.Medium, Enum.FontStyle.Normal)
	TextLabel.Text = "Segment Length"
	TextLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
	TextLabel.TextSize = 14
	TextLabel.TextXAlignment = Enum.TextXAlignment.Right
	TextLabel.AnchorPoint = Vector2.new(1, 0)
	TextLabel.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	TextLabel.BackgroundTransparency = 1
	TextLabel.Position = UDim2.fromScale(0.55, 0)
	TextLabel.Size = UDim2.fromScale(0.55, 1)
	TextLabel.Parent = Length

	local TextBox = Instance.new("TextBox")
	TextBox.Name = "TextBox"
	TextBox.FontFace =
		Font.new("rbxasset://fonts/families/GothamSSm.json", Enum.FontWeight.Medium, Enum.FontStyle.Normal)
	TextBox.Text = "20"
	TextBox.TextColor3 = Color3.fromRGB(248, 248, 248)
	TextBox.TextSize = 14
	TextBox.BackgroundColor3 = Color3.fromRGB(54, 54, 54)
	TextBox.BorderColor3 = Color3.fromRGB(45, 45, 45)
	TextBox.Position = UDim2.fromScale(0.6, 0)
	TextBox.Size = UDim2.fromScale(0.2, 1)
	TextBox.Parent = Length

	local TextLabel1 = Instance.new("TextLabel")
	TextLabel1.Name = "TextLabel"
	TextLabel1.FontFace =
		Font.new("rbxasset://fonts/families/GothamSSm.json", Enum.FontWeight.Medium, Enum.FontStyle.Normal)
	TextLabel1.Text = "studs"
	TextLabel1.TextColor3 = Color3.fromRGB(255, 255, 255)
	TextLabel1.TextSize = 14
	TextLabel1.TextXAlignment = Enum.TextXAlignment.Left
	TextLabel1.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	TextLabel1.BackgroundTransparency = 1
	TextLabel1.Position = UDim2.fromScale(0.82, 0)
	TextLabel1.Size = UDim2.fromScale(0.05, 1)
	TextLabel1.Parent = Length

	Length.Parent = Gui1

	local CurrentSelection = Instance.new("TextLabel")
	CurrentSelection.Name = "CurrentSelection"
	CurrentSelection.FontFace = Font.new("rbxasset://fonts/families/GothamSSm.json")
	CurrentSelection.Text = "Selected: None"
	CurrentSelection.TextColor3 = Color3.fromRGB(248, 248, 248)
	CurrentSelection.TextSize = 14
	CurrentSelection.TextWrapped = true
	CurrentSelection.Active = true
	CurrentSelection.BackgroundColor3 = Color3.fromRGB(54, 54, 54)
	CurrentSelection.BackgroundTransparency = 1
	CurrentSelection.BorderColor3 = Color3.fromRGB(45, 45, 45)
	CurrentSelection.Selectable = true
	CurrentSelection.Size = UDim2.fromScale(1, 0.14)
	CurrentSelection.Parent = Gui1

	local TextLabel2 = Instance.new("TextLabel")
	TextLabel2.Name = "TextLabel"
	TextLabel2.FontFace =
		Font.new("rbxasset://fonts/families/GothamSSm.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
	TextLabel2.Text = "Settings"
	TextLabel2.TextColor3 = Color3.fromRGB(248, 248, 248)
	TextLabel2.TextSize = 16
	TextLabel2.Active = true
	TextLabel2.AnchorPoint = Vector2.new(0.5, 0.5)
	TextLabel2.BackgroundColor3 = Color3.fromRGB(54, 54, 54)
	TextLabel2.BackgroundTransparency = 1
	TextLabel2.BorderColor3 = Color3.fromRGB(45, 45, 45)
	TextLabel2.BorderSizePixel = 0
	TextLabel2.Position = UDim2.fromScale(0.5, 0.475)
	TextLabel2.Selectable = true
	TextLabel2.Size = UDim2.new(0.5, 0, 0, 30)
	TextLabel2.Parent = Gui1

	local SetTemplateButton = Instance.new("TextButton")
	SetTemplateButton.Name = "SetTemplateButton"
	SetTemplateButton.FontFace =
		Font.new("rbxasset://fonts/families/GothamSSm.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
	SetTemplateButton.Text = "Select Track"
	SetTemplateButton.TextColor3 = Color3.fromRGB(248, 248, 248)
	SetTemplateButton.TextSize = 14
	SetTemplateButton.TextWrapped = true
	SetTemplateButton.AnchorPoint = Vector2.new(0.5, 0)
	SetTemplateButton.BackgroundColor3 = Color3.fromRGB(54, 54, 54)
	SetTemplateButton.BorderColor3 = Color3.fromRGB(45, 45, 45)
	SetTemplateButton.Position = UDim2.fromScale(0.5, 0.15)
	SetTemplateButton.Size = UDim2.fromScale(0.4, 0.1)
	SetTemplateButton.Parent = Gui1

	local Canting = Instance.new("Frame")
	Canting.Name = "Canting"
	Canting.AnchorPoint = Vector2.new(0.5, 0.5)
	Canting.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	Canting.BackgroundTransparency = 1
	Canting.Position = UDim2.fromScale(0.5, 0.725)
	Canting.Size = UDim2.fromScale(1, 0.08)

	local TextLabel3 = Instance.new("TextLabel")
	TextLabel3.Name = "TextLabel"
	TextLabel3.FontFace =
		Font.new("rbxasset://fonts/families/GothamSSm.json", Enum.FontWeight.Medium, Enum.FontStyle.Normal)
	TextLabel3.Text = "Canting Angle"
	TextLabel3.TextColor3 = Color3.fromRGB(255, 255, 255)
	TextLabel3.TextSize = 14
	TextLabel3.TextXAlignment = Enum.TextXAlignment.Right
	TextLabel3.AnchorPoint = Vector2.new(1, 0)
	TextLabel3.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	TextLabel3.BackgroundTransparency = 1
	TextLabel3.Position = UDim2.fromScale(0.55, 0)
	TextLabel3.Size = UDim2.fromScale(0.55, 1)
	TextLabel3.Parent = Canting

	local TextBox1 = Instance.new("TextBox")
	TextBox1.Name = "TextBox"
	TextBox1.FontFace =
		Font.new("rbxasset://fonts/families/GothamSSm.json", Enum.FontWeight.Medium, Enum.FontStyle.Normal)
	TextBox1.Text = "0"
	TextBox1.TextColor3 = Color3.fromRGB(248, 248, 248)
	TextBox1.TextSize = 14
	TextBox1.BackgroundColor3 = Color3.fromRGB(54, 54, 54)
	TextBox1.BorderColor3 = Color3.fromRGB(45, 45, 45)
	TextBox1.Position = UDim2.fromScale(0.6, 0)
	TextBox1.Size = UDim2.fromScale(0.2, 1)
	TextBox1.Parent = Canting

	local TextLabel4 = Instance.new("TextLabel")
	TextLabel4.Name = "TextLabel"
	TextLabel4.FontFace =
		Font.new("rbxasset://fonts/families/GothamSSm.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
	TextLabel4.Text = [[°
	]]
	TextLabel4.TextColor3 = Color3.fromRGB(255, 255, 255)
	TextLabel4.TextSize = 14
	TextLabel4.TextXAlignment = Enum.TextXAlignment.Left
	TextLabel4.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	TextLabel4.BackgroundTransparency = 1
	TextLabel4.Position = UDim2.fromScale(0.82, 0)
	TextLabel4.Size = UDim2.fromScale(0.05, 1)
	TextLabel4.Parent = Canting

	Canting.Parent = Gui1

	local Gradient = Instance.new("TextLabel")
	Gradient.Name = "Gradient"
	Gradient.FontFace =
		Font.new("rbxasset://fonts/families/GothamSSm.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
	Gradient.Text = "Flat"
	Gradient.TextColor3 = Color3.fromRGB(248, 248, 248)
	Gradient.TextSize = 16
	Gradient.Active = true
	Gradient.AnchorPoint = Vector2.new(0.5, 0.5)
	Gradient.BackgroundColor3 = Color3.fromRGB(54, 54, 54)
	Gradient.BackgroundTransparency = 1
	Gradient.BorderColor3 = Color3.fromRGB(45, 45, 45)
	Gradient.BorderSizePixel = 0
	Gradient.Position = UDim2.fromScale(0.5, 0.338)
	Gradient.Selectable = true
	Gradient.Size = UDim2.new(0.5, 0, 0, 30)
	Gradient.Parent = Gui1

	Gui1.Parent = Assets

	return Assets
end
